# Generated by Django 3.2.9 on 2022-01-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, unique=True, verbose_name='текст вопроса')),
                ('right_choices', models.SmallIntegerField(choices=[(1, 'Один правильный вариант ответа'), (2, 'Два правильных варианта ответа')], max_length=1, verbose_name='количество верных ответов')),
            ],
            options={
                'verbose_name': 'вопросы',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='текст ответа')),
                ('is_correct', models.BooleanField(verbose_name='верный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ответы',
                'verbose_name_plural': 'ответы',
            },
        ),
    ]
