# Generated by Django 3.2.9 on 2022-01-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'опросы',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='right_choices',
            field=models.SmallIntegerField(choices=[(1, 'Один правильный вариант ответа'), (2, 'Два правильных варианта ответа')], verbose_name='количество верных ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.quiz', verbose_name='опрос'),
            preserve_default=False,
        ),
    ]
