# Generated by Django 3.2.9 on 2022-01-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220117_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
