# Generated by Django 3.2.9 on 2022-01-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220118_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(limit_choices_to=4, on_delete=django.db.models.deletion.CASCADE, to='main_app.question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_choices',
            field=models.SmallIntegerField(choices=[(1, 'Один правильный вариант ответа'), (2, 'Два правильных варианта ответа')], default=1, verbose_name='количество верных ответов'),
        ),
    ]
